services:

  waf:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: waf-server
    network_mode: "host"
    volumes:
      - ./src/vnf:/app/vnf
      - ./results:/app/results
    command: ["python3", "/app/vnf/waf.py"]

  observador:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: observador
    network_mode: "host"
    pid: "host"
    volumes:
      - ./src/vnf:/app/vnf
      - ./results:/app/results
    command: ["python3", "/app/vnf/observador_sysstat.py"]
    depends_on:
      - waf

  client:
    build:
      context: .
      dockerfile: configs/Dockerfile.client
    container_name: socket-client
    network_mode: "host"
    environment:
      - PAYLOADS_FILE=${PAYLOADS_FILE}
      - WORKERS=${WORKERS:-200}
    volumes:
      - ./src/client:/app
      - ./data/payloads:/app/payloads:ro
    command: ["python3", "/app/client.py"]
    depends_on:
      - waf

  sysstat-collector:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: sysstat-collector
    network_mode: "host"
    environment:
      - COLLECTOR=sysstat
      - RESULTS_PATH=${RESULTS_PREFIX_CONT:-/app/results}/sysstat_${NUM_MESSAGES:-100}_run${RUN_ID:-1}_results.json
      - DURATION=${DURATION:-100}
    volumes:
      - ./src:/app/src
      - ./results:/app/results
    command: ["python3", "/app/src/probe.py"]
    depends_on:
      - observador

