services:

  waf:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: waf-server
    network_mode: "host"
    volumes:
      - ./src/vnf:/app/vnf
      - results_vol:/app/results
    command: python3 /app/vnf/waf.py

  monitor-server:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: monitor-server
    network_mode: "host"
    pid: "host"
    volumes:
      - ./src/vnf:/app/vnf
      - results_vol:/app/results
    command: python3 /app/vnf/monitor_prometheus.py
    depends_on:
      - waf

  client:
    build:
      context: .
      dockerfile: configs/Dockerfile.client
    container_name: socket-client
    network_mode: "host"
    environment:
      - NUM_MESSAGES=${NUM_MESSAGES:-100}
    volumes:
      - ./src/client:/app
    command: python3 /app/client.py
    depends_on:
      - waf

  prometheus-collector:
    build:
      context: .
      dockerfile: configs/Dockerfile
    container_name: prometheus-collector
    network_mode: "host"
    environment:
      - COLLECTOR=prometheus
      - RESULTS_PATH=/app/results/prometheus_${NUM_MESSAGES:-100}_run${RUN_ID:-1}_results.json
      - DURATION=${DURATION:-100}
    volumes:
      - ./src:/app/src
      - results_vol:/app/results
    command: python3 /app/src/probe.py
    depends_on:
      - monitor-server

volumes:
  results_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/results
